---
ID: "df9c3136-2cef-40c3-bbf8-7f59affc0762"
Parent: "e4ada2d0-2369-4a2c-9ab1-853ff099767c"
Template: "e4ada2d0-2369-4a2c-9ab1-853ff099767c"
Path: /sitecore/templates/Feature/SitecoreShades/Blog/Category/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20220814T174159Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\Admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "fd73762a-746f-47fe-a9d8-b8f446fecde2"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Admin
    - ID: "caa141dd-7584-4aba-8ba4-342b5e7359cd"
      Hint: CategoryName
      Value: $name
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20220814T174204Z
