---
ID: "cffad645-65f4-4672-b06d-1f23c6b986fd"
Parent: "68eb0c8e-fc09-4f39-b65e-fedd38d4b81f"
Template: "68eb0c8e-fc09-4f39-b65e-fedd38d4b81f"
Path: /sitecore/templates/Feature/SitecoreShades/Blog/Rendering Parameters/Blog Details/__Standard Values
SharedFields:
- ID: "3094d236-5985-4c4f-ae6a-e30740885532"
  Hint: Caching
  Value: 0|0|0|0|0|0|0|0
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20120629T104300
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "8dba5dc4-5a8e-4080-aeb6-875f6618634c"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20220825T055754Z
