---
ID: "f835a272-99b2-4b70-ab40-0b4b4cc2b383"
Parent: "5dc426e3-8a64-4a23-98a7-dffc08cfb2db"
Template: "f86fe270-00a4-492f-bfaf-5bf27e40ce13"
Path: /sitecore/content/SitecoreShades/StandBlog/Settings/Datasource Configurations
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20220802T162909Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\Admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "596ad04f-c26d-4fe6-8347-a372898fcd8a"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20220802T162909Z
